### PR TITLE
fix: support using custom chromosome names in genomic domains (`GenomicDomain`); fix `zoomTo()`

### LINKED ISSUE #793: `GenomicDomain` doesn't support custom chromsizes
The `Chromosome` type is hard-coded with human genome name literals (e.g. "chr1", "1", ...). In Gos, this causes an issue where you cannot initialize the domain for the visualization for the named chromosomes:

```python
gos.overlay(...).properties(
   assembly=[["NC_045512.2", 29903]],
   xDomain=gos.GenomicDomain(chromosome="NC_045512.2", interval=[1, 29903]),
 )
# Error!!! chromsome not one of "chr1" ... 
```

Chromosome should just be a `string`. I think we should try to avoid any magic with coercing chromosome names (e.g., (`name.replace("chr", "")`) since this gets quite complicated. Although as mentioned in #709, perhaps some fuzzy-ness is useful? In that case I would be extremely explicit about how coercion works and have a utility which does this (and can be tested carefully). i.e.,

```typescript
// returns valid key of assembly _or_ throws
function coerceChromIdentifier<
  Sizes extends Record<string, number>
>(name: string, sizes: Sizes): keyof Sizes {
  // exact match
  if (name in sizes) return name;
  
  let test;
  // strip chr prefix
  test = name.slice("chr".length)
  if (test in sizes) return test;

  // append chr prefix
  test = "chr" + name;
  if (test in sizes) return test;

  throw new Error("invalid identifier, could not be coerced");
}
```

### PR DESCRIPTION
**Pull request by sehilyi**
Fix #793

## Change List
 - Change the type of `chromosome` to `string` so that any custom chromosome names can be used.
 - Removes some magics about handling chromosome names which were really unnecessary.
 - Change all demo examples that used chromosome names without the "chr" prefix.

## Checklist
 - [x] Ensure the PR works with all demos on the online editor
 - [x] Unit tests added or updated
 - [ ] Examples added or updated
 - [ ] [Documentation](https://github.com/gosling-lang/gosling-website) updated (e.g., added API functions)
 - [ ] Screenshots for visual changes (e.g., new encoding support or UI change on Editor)

### CODE REVIEW

File: src/core/api.ts [hunk 1]
```diff
@@ -99,7 +99,7 @@ export function createApi(
             const parsed = parseGenomicPosition(position);
             const { chromosome: chr } = parsed;
             let { start, end } = parsed;
-            if (!chr || chromInfo.interval[chr]) {
+            if (!chr || !chromInfo.interval[chr]) {
```
Comment (sehilyi) [inline src/core/api.ts]: I think this was a bug

Comment (sehilyi) [reply src/core/api.ts]: I wonder if we can set up tests for the APIs not to break things.

File: src/core/gosling.schema.ts [hunk 2]
```diff
@@ -766,18 +764,18 @@ export interface ChannelValue {
 export type AxisPosition = 'none' | 'top' | 'bottom' | 'left' | 'right';
 export type FieldType = 'genomic' | 'nominal' | 'quantitative';
 export type ValueExtent = string[] | number[];
-export type GenomicDomain = DomainInterval | DomainChrInterval | DomainChr | DomainGene;
```
Comment (sehilyi) [inline src/core/gosling.schema.ts:769]: This `DomainGene` was never supported, so let's remove this and add it back whenever we support it.

File: src/core/api.ts (hunk 1 above)
Comment (manzt) [reply src/core/api.ts]: > I wonder if we can set up tests for the APIs not to break things.

It would be challenging to test the API end-to-end since it requires the HiGlass API (running in the browser). I think breaking apart some of the logic here into separate functions which we can unit test separately would be best.


 i.e., a class which handles this behavior and we can test with different assemblies/chromInfos.

```typescript

class GenomicPosition {
  constructor(public chr: string, public start?: number, public end?: number) {}
  static fromString(s: string) { 
    const result = parseGenomicPosition(position);
    return new GenomicPosition(result.chromosome, result.start, result.end);
  }
  toAbsoluteCoordinates(assemby: Assembly, padding = 0): [number, number] {
     let info = GET_CHROM_SIZES(assembly);
     let size = info.size[this.chr];
     let interval = info.interval[this.chr];
     if (size === undefined || interval === undefined) {
       throw Error(`Chromosome name ${this.chr} is not valid`);
     }
     let { start, end } = this;
     if (start === undefined || end === undefined) {
         [start, end] = [0, size];
     }
     const offset = info.interval[0];
     return [start + offset - padding, end + offset + padding]
  }
}
```

Comment (manzt) [reply src/core/api.ts]: then the zoomTo implementation would turn into:

```typescript

function zoomTo(viewId: string, positionString: string, padding = 0, duration = 1000) {
  const assembly = getTrack(viewId)?.spec.assembly;
  const position = GenomicPosition.fromString(positionString);
  let coordinates: [number, number];
  try {
    coordinates = position.toAbsoluteCoordinates(assembly);
  } catch (e) {
     console.warn("chromosome is not valid")
     return;
  }
  hg.api.zoomTo(viewId, ...coordinates, ...coordinates, duration);
}

```

Comment (manzt) [reply src/core/api.ts]: and we could test the `GenomicPosition` class for a variety of positions and assemblies and assert the correct behavior

File: src/core/gosling.schema.ts (hunk 2 above)
Comment (manzt) [reply src/core/gosling.schema.ts:769]: I agree with this decision. Genes are ultimately entities which correspond to intervals of genomic coordinates. There are many other genomic features which have this same property, and I don't see a motivating case to add specific support for "genes".

Comment (manzt) [reply src/core/gosling.schema.ts:769]: It should be simple enough to map _any_ table of features which are defined by to genomic coordinates (other columns in the table) with the current API.

File: src/core/utils/scales.ts [hunk 3]
```diff
@@ -1,43 +1,32 @@
...
         return [
-            GET_CHROM_SIZES(assembly).interval[`chr${domain.chromosome}`][0] + 1,
-            GET_CHROM_SIZES(assembly).interval[`chr${domain.chromosome}`][1]
+            GET_CHROM_SIZES(assembly).interval[domain.chromosome][0] + 1,
+            GET_CHROM_SIZES(assembly).interval[domain.chromosome][1]
         ];
     } else if (IsDomainInterval(domain)) {
         return domain.interval;
     } else if (IsDomainChrInterval(domain)) {
-        const chrStart = GET_CHROM_SIZES(assembly).interval[`chr${domain.chromosome}`][0];
```
Comment (manzt) [inline src/core/utils/scales.ts]: I would suggest calling `GET_CHROM_SIZES(assembly)` once in this function and then reusing the returned object. Remember that this function currently creates `URL` objects on every invocation.

I see this pattern a lot in the repo, I think that it stems from the `GET_CHROM_SIZES` name appearing to be a constant (where in fact it is a function that has non-trival overhead of computing). My I suggest renaming `GET_CHROM_SIZES` to `calculateChromsizes` or `computeChromsizes` so that this is more clear?

**Review by manzt — APPROVED** [review]

File: src/core/utils/scales.ts (hunk 3 above)
Comment (sehilyi) [reply src/core/utils/scales.ts]: Renaming the function is a good idea. I took the name `computeChromSizes`.

File: src/core/api.ts (hunk 1 above)
Comment (sehilyi) [reply src/core/api.ts]: I've updated the codes accordingly in [the last commit](https://github.com/gosling-lang/gosling.js/pull/796/commits/846da78d83480c44ac56aad687db1f90cd596d7f). I think we can expand this class and reuse it throughout the codes.
