### PR TITLE
fix(data-fetcher): correctly calculate the distance to previous mutation in VCF (`DISTPREV`)

### LINKED ISSUE #948: Incorrect `DISTPREV` after chr 1 in VCF data
Screenshot 2023-07-21 at 11 34 52
```ts
{
   "tracks":[
      {
         "id":"SRR7890905-mid-mutation",
         "title":"Point Mutation",
         "style":{
            "background":"#FFFFFF",
            "inlineLegend":true
         },
         "data":{
            "type":"vcf",
            "url":"https://somatic-browser-test.s3.amazonaws.com/SNV_test_tumor_normal_with_panel.vcf.gz",
            "indexUrl":"https://somatic-browser-test.s3.amazonaws.com/SNV_test_tumor_normal_with_panel.vcf.gz.tbi",
            "sampleLength":500
         },
         "dataTransform":[
            {
               "field":"DISTPREV",
               "type":"filter",
               "oneOf":[
                  0
               ],
               "not":true
            }
         ],
         "mark":"point",
         "x":{
            "field":"POS",
            "type":"genomic"
         },
         "color":{
            "field":"SUBTYPE",
            "type":"nominal",
            "legend":true,
            "domain":[
               "C>A",
               "C>G",
               "C>T",
               "T>A",
               "T>C",
               "T>G"
            ]
         },
         "y":{
            "field":"DISTPREVLOGE",
            "type":"quantitative",
            "axis":"left",
            "range":[
               10,
               50
            ]
         },
         "opacity":{
            "value":0.9
         },
         "tooltip":[
            {
               "field":"DISTPREV",
               "type":"nominal",
               "format":"s1",
               "alt":"Distance To Previous Mutation (BP)"
            },
            {
               "field":"POS",
               "type":"genomic"
            },
            {
               "field":"SUBTYPE",
               "type":"nominal"
            }
         ],
         "width":680,
         "height":60
      }
   ]
}
```

### PR DESCRIPTION
**Pull request by sehilyi**
Fix #948 
Toward #

## Change List
 -

## Checklist
 - [ ] Ensure the PR works with all demos on the online editor
 - [x] Unit tests added or updated
 - [ ] Examples added or updated
 - [ ] [Documentation](https://github.com/gosling-lang/gosling-website) updated (e.g., added API functions)
 - [ ] Screenshots for visual changes (e.g., new encoding support or UI change on Editor)

### CODE REVIEW

File: src/data-fetchers/vcf/utils.ts [hunk 1]
```diff
@@ -48,8 +48,8 @@ export function recordToTile(vcfRecord: VcfRecord, chrPos: number, prevPos?: num
     }
 
     // Additionally inferred values
-    const DISTPREV = !prevPos ? null : vcfRecord.POS - prevPos;
-    const DISTPREVLOGE = !prevPos ? null : Math.log(vcfRecord.POS - prevPos);
+    const DISTPREV = !prevPos ? null : POS - prevPos;
```
Comment (sehilyi) [inline src/data-fetchers/vcf/utils.ts]: `prevPos` is the absolute genomic position, but `vcfRecord.POS` is the relative one. Using `POS` instead which is defined a few lines above:

```ts
const POS = chrPos + vcfRecord.POS + 1;
```
