### PR TITLE
fix(core): Flipped y-axis stacked bar chart

### LINKED ISSUE #1041: Flipping Stacked Barcharts fails
I am building a viewer with stacked bars, one row for each strand (+,-). I wanted to flip the reserve strand, but this returned a weird visualization. 
```
[...]
"y": {
                    "field": "count",
                    "type": "quantitative",
                    axis: "left",
                    domain: [0, maxValueBin[strand]],
                    range: [0, 90], flip: strand === "-"
                } 
[...]
```
image

I was able to reproduce the problem with the semantic zooming example (https://gosling.js.org/?example=SEQUENCE), where similar stacked bar charts are used. 

image

Is this expected behavior, and I am just not understanding the flip-key correctly, or is it a bug?

### PR DESCRIPTION
**Pull request by etowahadams**
Fix #1041
Toward #

## Change List
 - Fix stacked bar mark when y-axis is flipped. 

```
{"arrangement": "vertical","views": [{"xDomain": {"chromosome": "chr1", "interval": [3000000, 3002010]},"title": "Flipped: true","layout": "linear","alignment": "overlay","data": {"url": "https://server.gosling-lang.org/api/v1/tileset_info/?d=sequence-multivec","type": "multivec","row": "base","column": "position","value": "count","categories": ["A", "T", "G", "C"],"start": "start","end": "end"},"tracks": [{"mark": "bar","id": "flipped-track","y": {"field": "count","type": "quantitative","axis": "none","flip": true}},{"dataTransform": [{"type": "filter", "field": "count", "oneOf": [0], "not": true}],"mark": "text","x": {"field": "start", "type": "genomic"},"xe": {"field": "end", "type": "genomic"},"size": {"value": 24},"color": {"value": "white"},"visibility": [{"operation": "less-than","measure": "width","threshold": "|xe-x|","transitionPadding": 30,"target": "mark"},{"operation": "LT","measure": "zoomLevel","threshold": 40,"target": "track"}]}],"x": {"field": "position", "type": "genomic"},"color": {"field": "base","type": "nominal","domain": ["A", "T", "G", "C"],"legend": true},"text": {"field": "base", "type": "nominal"},"style": {"textFontWeight": "bold"},"width": 800,"height": 100},{"layout": "linear","title": "Flipped: false","xDomain": {"chromosome": "chr1", "interval": [3000000, 3002010]},"alignment": "overlay","data": {"url": "https://server.gosling-lang.org/api/v1/tileset_info/?d=sequence-multivec","type": "multivec","row": "base","column": "position","value": "count","categories": ["A", "T", "G", "C"],"start": "start","end": "end"},"tracks": [{"id": "not-flipped-track","mark": "bar","y": {"field": "count","type": "quantitative","axis": "none","flip": false}},{"dataTransform": [{"type": "filter", "field": "count", "oneOf": [0], "not": true}],"mark": "text","x": {"field": "start", "type": "genomic"},"xe": {"field": "end", "type": "genomic"},"size": {"value": 24},"color": {"value": "white"},"visibility": [{"operation": "less-than","measure": "width","threshold": "|xe-x|","transitionPadding": 30,"target": "mark"},{"operation": "LT","measure": "zoomLevel","threshold": 40,"target": "track"}]}],"x": {"field": "position", "type": "genomic"},"color": {"field": "base","type": "nominal","domain": ["A", "T", "G", "C"],"legend": true},"text": {"field": "base", "type": "nominal"},"style": {"textFontWeight": "bold"},"width": 800,"height": 100}]}
```

Before:
image
After:
image

## Circular layout 
Before:
image

After:
image

## Checklist
 - [x] Ensure the PR works with all demos on the online editor
 - [ ] Unit tests added or updated
 - [ ] Examples added or updated
 - [ ] [Documentation](https://github.com/gosling-lang/gosling-website) updated (e.g., added API functions)
 - [x] Screenshots for visual changes (e.g., new encoding support or UI change on Editor)

### CODE REVIEW

File: src/tracks/gosling-track/gosling-track.ts [hunk 1]
```diff
@@ -1011,7 +1011,7 @@ const factory: PluginTrackFactory<Tile, GoslingTrackOptions> = (HGC, context, op
 
                 // Replace width and height information with the actual values for responsive encoding
                 const [trackWidth, trackHeight] = this.dimensions; // actual size of a track
-                const axisSize = IsXAxis(resolvedSpec) ? HIGLASS_AXIS_SIZE : 0; // Why the axis size must be added here?
+                const axisSize = IsXAxis(resolvedSpec) && this.options.spec.layout === 'linear' ? HIGLASS_AXIS_SIZE : 0; // Why the axis size must be added here?
```
Comment (etowahadams) [inline src/tracks/gosling-track/gosling-track.ts:1014]: Circular tracks were receiving the incorrect track height because height was being added here.

File: src/core/mark/bar.ts [hunk 2]
```diff
@@ -89,8 +90,12 @@ export function drawBar(track: any, tile: Tile, model: GoslingTrackModel) {
                 const alphaTransition = model.markVisibility(d, { width: barWidth, zoomLevel });
                 const actualOpacity = Math.min(alphaTransition, opacity);
 
-                if (actualOpacity === 0 || barWidth <= 0 || y <= 0) {
-                    // do not draw invisible marks
+                if (
+                    actualOpacity === 0 ||
+                    barWidth <= 0 ||
+                    (isFlippedY && y - rowHeight >= 0) ||
+                    (!isFlippedY && y <= 0)
```
Comment (etowahadams) [inline src/core/mark/bar.ts:97]: Add some extra conditions to keep incorrect draws from occurring

File: src/tracks/gosling-track/gosling-track.ts (hunk 1 above)
Comment (sehilyi) [reply src/tracks/gosling-track/gosling-track.ts:1014]: Ah, good catch.

**Review by sehilyi — APPROVED** [review]
Thank you for the fix!!

**Comment by sehilyi** [comment]
I will patch gosling.js once this is merged!

**Comment by sehilyi** [comment]
Oh, actually will increase the minor version considering https://github.com/gosling-lang/gosling.js/pull/1044
